# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motor.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MotorControl(object):
    def setupUi(self, MotorControl):
        MotorControl.setObjectName("MotorControl")
        MotorControl.resize(655, 283)
        self.progressBar = QtWidgets.QProgressBar(MotorControl)
        self.progressBar.setGeometry(QtCore.QRect(0, 220, 311, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.speedControl = QtWidgets.QSlider(MotorControl)
        self.speedControl.setGeometry(QtCore.QRect(100, 70, 401, 22))
        self.speedControl.setMinimum(0)
        self.speedControl.setMaximum(200)
        self.speedControl.setProperty("value", 200)
        self.speedControl.setOrientation(QtCore.Qt.Horizontal)
        self.speedControl.setInvertedAppearance(True)
        self.speedControl.setInvertedControls(False)
        self.speedControl.setObjectName("speedControl")
        self.step = QtWidgets.QLabel(MotorControl)
        self.step.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.step.setObjectName("step")
        self.spinSpeed = QtWidgets.QLabel(MotorControl)
        self.spinSpeed.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.spinSpeed.setObjectName("spinSpeed")
        self.Deg = QtWidgets.QLabel(MotorControl)
        self.Deg.setGeometry(QtCore.QRect(510, 20, 121, 31))
        self.Deg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Deg.setAutoFillBackground(True)
        self.Deg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Deg.setWordWrap(False)
        self.Deg.setOpenExternalLinks(False)
        self.Deg.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Deg.setObjectName("Deg")
        self.sequaence = QtWidgets.QLabel(MotorControl)
        self.sequaence.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.sequaence.setObjectName("sequaence")
        self.move = QtWidgets.QPushButton(MotorControl)
        self.move.setGeometry(QtCore.QRect(490, 210, 151, 41))
        self.move.setObjectName("move")
        self.speed = QtWidgets.QLabel(MotorControl)
        self.speed.setGeometry(QtCore.QRect(510, 70, 131, 20))
        self.speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speed.setObjectName("speed")
        self.angleSelector = QtWidgets.QSlider(MotorControl)
        self.angleSelector.setGeometry(QtCore.QRect(100, 20, 411, 24))
        self.angleSelector.setMaximum(800)
        self.angleSelector.setSliderPosition(2)
        self.angleSelector.setOrientation(QtCore.Qt.Horizontal)
        self.angleSelector.setInvertedAppearance(True)
        self.angleSelector.setInvertedControls(True)
        self.angleSelector.setObjectName("angleSelector")
        self.warnning = QtWidgets.QLabel(MotorControl)
        self.warnning.setGeometry(QtCore.QRect(170, 110, 181, 20))
        self.warnning.setObjectName("warnning")
        self.seqSel = QtWidgets.QSpinBox(MotorControl)
        self.seqSel.setGeometry(QtCore.QRect(140, 150, 108, 36))
        self.seqSel.setMaximum(2)
        self.seqSel.setObjectName("seqSel")
        self.adjVlaue = QtWidgets.QTextEdit(MotorControl)
        self.adjVlaue.setGeometry(QtCore.QRect(370, 150, 161, 31))
        self.adjVlaue.setObjectName("adjVlaue")
        self.adj = QtWidgets.QLabel(MotorControl)
        self.adj.setGeometry(QtCore.QRect(280, 160, 101, 20))
        self.adj.setObjectName("adj")
        self.adjLabel = QtWidgets.QLabel(MotorControl)
        self.adjLabel.setGeometry(QtCore.QRect(540, 160, 31, 21))
        self.adjLabel.setObjectName("adjLabel")
        self.doAdj = QtWidgets.QPushButton(MotorControl)
        self.doAdj.setGeometry(QtCore.QRect(320, 210, 151, 41))
        self.doAdj.setObjectName("doAdj")

        self.retranslateUi(MotorControl)
        QtCore.QMetaObject.connectSlotsByName(MotorControl)

    def retranslateUi(self, MotorControl):
        _translate = QtCore.QCoreApplication.translate
        MotorControl.setWindowTitle(_translate("MotorControl", "Dialog"))
        self.step.setText(_translate("MotorControl", "Angle"))
        self.spinSpeed.setText(_translate("MotorControl", "motorspeed"))
        self.Deg.setText(_translate("MotorControl", "<html><head/><body><p><span style=\" font-size:14pt;\">Deg</span></p></body></html>"))
        self.sequaence.setText(_translate("MotorControl", "spin sequance"))
        self.move.setText(_translate("MotorControl", "move"))
        self.speed.setText(_translate("MotorControl", "Deg/s"))
        self.warnning.setText(_translate("MotorControl", "fast speed makes big error"))
        self.adj.setText(_translate("MotorControl", "Adjustment"))
        self.adjLabel.setText(_translate("MotorControl", "Deg"))
        self.doAdj.setText(_translate("MotorControl", "Adj"))

